# try:
#     x=4
#     print(x.length) 
# except(NameError,AttributeError):
#     print("something went wrong")
# else:
#     print("No Error was found")
# finally:
#     print("Program Completed")

x=5
if x>1:
    raise Exception("X cannot be greater than 1")